### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by yammadev** [shultzer/Blog#1]
Hi there,

I saw your post in a facebook group and I felt curious to give it a try. I'll definetly do it. On the other hand,  I think it would be better if you add a readme with some kind of guideance or instruction to extend this boilerplate for those who are seeking and simple solution. 

Regards,

**Comment by shultzer** [comment]
A multi-user web application with the ability to keep their blogs and comment on articles from other users. Functionality for adding articles appears after registration or logging in of the registered user. Database relations -  one to many and many to many. Migrations are written. Ability to edit and delete only your articles.
